#!/usr/bin/env bash
# setup a load balancer
FRONTEND="frontend Local_server\n\tbind *:80\n\tmode http\n\tdefault_backend my_web_servers"
BACKEND="backend my_web_servers\n\tmode http\n\tbalance roundrobin\n\tserver 291-web-01 34.75.72.161:80 check\n\tserver 291-web-02 34.73.112.255:80 check"
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo sed -i "\$a $FRONTEND" /etc/haproxy/haproxy.cfg
sudo sed -i "\$a $BACKEND" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
