#!/usr/bin/env bash
# display indefinitely
hexToAscii() {
  # shellcheck disable=SC2059
  printf "\x$1"
}
msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
