#!/usr/bin/env bash
# print the numbers from 1 to 20 and their superstition
i=1
while ((i < 21)); do
    echo "$i"
    case $i in
	4)
	  echo "bad luck from China"
	  ;;
	9)
	  echo "bad luck from Japan"
	  ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
