#!/bin/bash
sudo apt-get update
sudo apt-get -y install ufw

sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw allow 8080/tcp

sudo sed -i "1i*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT" /etc/ufw/before.rules
sudo ufw enable
