#!/usr/bin/env bash
# change the user nginx runs on and
# nginx listens to port 8080

sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

sudo chown nginx:nginx /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default

sudo sed -i 's/listen [::]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-available/default

pkill apche2
sudo -u nginx sudo service nginx restart
